/* Priangan Multimedia — App Shell
 * Owns bootstrap, shared Supabase connection, navigation and shell pages.
 * Domain pages are owned by their authoritative modules.
 */
(function(){
'use strict';
if(window.__PM_APP_SHELL_CORE)return;window.__PM_APP_SHELL_CORE=true;
const C=window.PRIANGAN_CONFIG||{};
let db=null,page='dashboard',masters=[],clients=[],template=null;
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
const active=v=>{if(v===true||v===1)return true;const s=String(v??'').trim().toUpperCase();return !['FALSE','0','NO','TIDAK','NONAKTIF','INACTIVE','OFF'].includes(s)};
const labels={dashboard:'Dashboard',master:'Master Harga',clients:'Data Client',quotation:'Buat Penawaran',history:'Riwayat Penawaran',invoice:'Invoice',finance:'Laporan Keuangan',vendors:'Data Vendor',template:'Template Surat',settings:'Pengaturan'};
function msg(text){const toast=$('#toast');if(!toast)return;toast.textContent=text;toast.classList.add('show');clearTimeout(window.__pmToastTimer);window.__pmToastTimer=setTimeout(()=>toast.classList.remove('show'),3000)}
function cfg(){return{url:String(C.SUPABASE_URL||'').trim(),key:String(C.SUPABASE_ANON_KEY||'').trim()}}
async function load(){if(!db)throw Error('Supabase belum terhubung.');const [mr,cr,tr]=await Promise.all([db.from('master_harga').select('*').order('id'),db.from('clients').select('*').order('id',{ascending:false}),db.from('template_surat').select('*').order('id',{ascending:false}).limit(1)]);if(mr.error)throw mr.error;if(cr.error)throw cr.error;if(tr.error)throw tr.error;masters=mr.data||[];clients=cr.data||[];template=tr.data?.[0]||null;window.masters=masters;window.clients=clients;window.template=template;window.db=db}
function syncNav(){document.querySelectorAll('.sidebar .nav[data-p]').forEach(b=>{const is=b.dataset.p===page;b.classList.toggle('active',is);if(is)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
function setCurrentPage(next){const normalized=String(next||'dashboard');if(!labels[normalized])return;page=normalized;window.page=page;syncNav();if($('#title'))$('#title').textContent=labels[page]}
function route(name){
  setCurrentPage(name);
  if(name==='dashboard'&&typeof window.pmRenderDashboardCyber==='function')return window.pmRenderDashboardCyber();
  if(name==='quotation')return quotationPage();
  if(name==='template')return templatePage();
  if(name==='settings')return settingsPage();
  const fn=window[name+'Page'];
  if(typeof fn==='function')return fn();
  const content=$('#content');if(content)content.innerHTML=`<div class="card"><h2>${esc(name)}</h2><p>Modul belum tersedia.</p></div>`;
}
function render(){syncNav();if($('#title'))$('#title').textContent=labels[page]||'Priangan Multimedia';return route(page)}
function dashboardPage(){setCurrentPage('dashboard');if(typeof window.pmRenderDashboardCyber==='function')return window.pmRenderDashboardCyber();const count=masters.filter(x=>active(x.aktif)).length;$('#content').innerHTML=`<div class="head"><div><h1>Dashboard</h1><p>Sales & quotation Priangan Multimedia.</p></div><button class="btn" type="button" onclick="go('quotation')">+ Buat Penawaran</button></div><div class="grid g4"><div class="card stat"><small>Master Harga Aktif</small><strong>${count}</strong></div><div class="card stat"><small>Client</small><strong>${clients.length}</strong></div><div class="card stat"><small>Template Surat</small><strong>${template?1:0}</strong></div><div class="card stat"><small>Database</small><strong style="font-size:20px">${db?'ONLINE':'OFFLINE'}</strong></div></div><div class="card" style="margin-top:16px"><b>Alur</b><p style="color:var(--muted)">Master Harga → Client → Penawaran → Preview A4 → Invoice → Pembayaran.</p></div>`}
function masterPage(){if(typeof window.pmMasterPage==='function')return window.pmMasterPage();const list=masters.filter(active);$('#content').innerHTML=`<div class="head"><div><h1>Master Harga</h1><p>Produk dan jasa.</p></div><button class="btn" type="button" onclick="masterForm()">+ Tambah Item</button></div><div class="card"><div class="scroll"><table class="table"><thead><tr><th>Kode</th><th>Item</th><th>Kategori</th><th>Satuan</th><th>Harga Modal</th><th>Harga Jual</th><th>Aktif</th></tr></thead><tbody>${list.map(r=>`<tr><td>${esc(r.kode)}</td><td>${esc(r.item)}</td><td>${esc(r.kategori)}</td><td>${esc(r.satuan)}</td><td>${money(r.harga_modal)}</td><td>${money(r.harga_jual)}</td><td>${active(r.aktif)?'YA':'TIDAK'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">Belum ada data.</td></tr>'}</tbody></table></div></div>`}
function masterForm(){if(typeof window.pmMasterForm==='function')return window.pmMasterForm();$('#content').insertAdjacentHTML('afterbegin',`<div id="masterForm" class="card" style="margin-bottom:16px"><div class="grid g2"><div class="field"><label>Kode</label><input id="mk"></div><div class="field"><label>Item</label><input id="mi"></div><div class="field"><label>Kategori</label><input id="mc"></div><div class="field"><label>Satuan</label><input id="ms"></div><div class="field"><label>Harga Modal</label><input id="hm" type="number" min="0" step="1"></div><div class="field"><label>Harga Jual</label><input id="mh" type="number" min="0" step="1"></div></div><div class="actions"><button class="btn secondary" type="button" onclick="document.getElementById('masterForm')?.remove()">Batal</button><button class="btn" type="button" onclick="saveMasterEditor()">Simpan</button></div></div>`);$('#mk')?.focus()}
async function saveMaster(){if(typeof window.pmSaveMaster==='function')return window.pmSaveMaster();return msg('Editor Master Harga belum siap.')}
function quotationPage(){
  setCurrentPage('quotation');
  const alreadyEditing=!!(window.__pmEditingQuotationId||window.__PM_EDIT_QUOTATION_ID);
  if(!alreadyEditing)window.items=[];
  $('#content').innerHTML=`<div class="head"><div><h1>${alreadyEditing?'Edit Surat Penawaran':'Buat Surat Penawaran'}</h1><p>Dimensi LED, Rigging, Level dan Qty dihitung otomatis.</p></div></div><div class="card"><b>Informasi Umum</b><div class="grid g2" style="margin-top:15px"><div class="field"><label>Client *</label><input id="qc" list="clientList" placeholder="Pilih / ketik nama client"><datalist id="clientList">${clients.map(c=>`<option value="${esc(c.nama_client)}"></option>`).join('')}</datalist></div><div class="field"><label>Perusahaan *</label><input id="qp"></div><div class="field"><label>No. Telepon / WA</label><input id="qw"></div><div class="field"><label>Email</label><input id="qe"></div><div class="field"><label>Nama Event / Project *</label><input id="qeve"></div><div class="field"><label>Tanggal Mulai Event</label><input id="qs" type="date"></div><div class="field"><label>Tanggal Selesai Event</label><input id="qe2" type="date"></div></div></div><div style="margin-top:20px"><div id="items"></div><div class="actions no-print"><button class="btn" type="button" onclick="addItem()">+ TAMBAH ITEM</button></div></div><div class="card" style="margin-top:16px"><div class="sum"><span>Total</span><b id="total">Rp 0</b></div><div class="actions no-print" style="margin-top:15px"><button class="btn secondary" type="button" onclick="go('dashboard')">Batal</button><button class="btn green" type="button" onclick="saveQuote()">Simpan Penawaran</button><button class="btn" type="button" onclick="printQuote()">Preview / Cetak A4</button></div></div>`;
  const input=$('#qc');input?.addEventListener('input',fillClient);input?.addEventListener('change',fillClient);
  if(alreadyEditing){if(typeof window.drawItems==='function')window.drawItems();}else if(typeof window.addItem==='function')window.addItem();
}
function fillClient(){const v=$('#qc')?.value.trim().toLowerCase();const c=clients.find(x=>String(x.nama_client||'').trim().toLowerCase()===v);if(!c)return;$('#qp').value=c.perusahaan||'';$('#qw').value=c.whatsapp||c.telepon||'';$('#qe').value=c.email||''}
function templatePage(){const t=template||{};$('#content').innerHTML=`<div class="head"><div><h1>Template Surat</h1><p>Kop, logo, ketentuan dan tanda tangan.</p></div></div><div class="grid g2"><div class="card">${tf('Nama Template','tn',t.nama_template)}${tf('Logo URL','tl',t.logo_url)}${tf('Kop Text','tk',t.kop_text)}${tf('Alamat','ta',t.alamat)}${tf('Telepon','tt',t.telepon)}${tf('WhatsApp','tw',t.whatsapp)}${tf('Email','te',t.email)}${tf('Website','tweb',t.website)}${tf('Ketentuan','tket',t.ketentuan,true)}${tf('Nama Penandatangan','tp',t.nama_penandatangan)}${tf('Jabatan','tj',t.jabatan_penandatangan)}${tf('TTD URL','ttd',t.ttd_url)}<div class="actions"><button class="btn" type="button" onclick="saveTemplate()">Simpan Template</button></div></div><div class="preview"><div class="kop">${t.logo_url?`<img src="${esc(t.logo_url)}" alt="Logo">`:''}<h2>${esc(t.kop_text||'PRIANGAN MULTIMEDIA')}</h2><div>${esc(t.alamat||'')}</div><div>${esc(t.telepon||'')}${t.whatsapp?' | WA '+esc(t.whatsapp):''}</div></div><h3 style="text-align:center">SURAT PENAWARAN HARGA</h3><p>Nomor: ____________________</p><p>Kepada Yth. __________________________</p><p>Dengan hormat, berikut kami sampaikan penawaran harga untuk kebutuhan event/project.</p><div style="font-size:10px"><b>Syarat & Ketentuan</b><br>${formatMultiline(t.ketentuan||'')}</div><div style="margin:40px 0 0 auto;width:220px;text-align:center">${t.ttd_url?`<img src="${esc(t.ttd_url)}" alt="TTD" style="max-height:80px;max-width:180px">`:''}<br><b>${esc(t.nama_penandatangan||'')}</b><br>${esc(t.jabatan_penandatangan||'')}</div></div></div>`}
function formatMultiline(v){return esc(v).replace(/\r?\n/g,'<br>')}
function tf(label,id,value,textarea=false){return `<div class="field"><label>${esc(label)}</label>${textarea?`<textarea id="${id}" rows="8">${esc(value||'')}</textarea>`:`<input id="${id}" value="${esc(value||'')}">`}</div>`}
async function saveTemplate(){if(!db)return msg('Supabase belum terhubung.');const payload={nama_template:$('#tn')?.value.trim()||'',logo_url:$('#tl')?.value.trim()||'',kop_text:$('#tk')?.value.trim()||'',alamat:$('#ta')?.value.trim()||'',telepon:$('#tt')?.value.trim()||'',whatsapp:$('#tw')?.value.trim()||'',email:$('#te')?.value.trim()||'',website:$('#tweb')?.value.trim()||'',ketentuan:$('#tket')?.value.trim()||'',nama_penandatangan:$('#tp')?.value.trim()||'',jabatan_penandatangan:$('#tj')?.value.trim()||'',ttd_url:$('#ttd')?.value.trim()||''};try{let r=template?.id?await db.from('template_surat').update(payload).eq('id',template.id).select('id').single():await db.from('template_surat').insert([payload]).select('id').single();if(r.error)throw r.error;if(!r.data?.id)throw Error('Database tidak mengembalikan ID template.');await load();render();msg('Template surat disimpan.')}catch(e){console.error('[PM] template save',e);msg('Gagal menyimpan template: '+(e.message||e))}}
function settingsPage(){const x=cfg();$('#content').innerHTML=`<div class="head"><div><h1>Pengaturan Database</h1><p>Koneksi Supabase ditetapkan oleh js/config.js.</p></div></div><div class="card"><div class="field"><label>URL Supabase</label><input value="${esc(x.url)}" readonly></div><div class="field"><label>Publishable / Anon Key</label><input value="${esc(x.key)}" readonly></div></div>`}
function go(next){const target=String(next||'dashboard');const editing=!!(window.__pmEditingQuotationId||window.__PM_EDIT_QUOTATION_ID);if(target!=='quotation'&&editing){window.__pmEditingQuotationId=null;window.__PM_EDIT_QUOTATION_ID=null;window.__pmEditingQuotationNumber=null;window.__PM_EDIT_QUOTATION_NUMBER=null;window.__pmDiscountBase=0;window.__pmDiscountValue=0;window.__pmDiscountPct=0;window.__pmNetTotal=0;window.__PM_DISC_MODE='rp';window.items=[];}page=target;window.page=page;if(page==='quotation'&&!editing){window.__pmEditingQuotationNumber=null;window.__PM_EDIT_QUOTATION_NUMBER=null;window.items=[];window.__PM_DISC_MODE='rp';window.__pmDiscountBase=0;window.__pmDiscountValue=0;window.__pmDiscountPct=0;window.__pmNetTotal=0}render()}
window.$=$;window.esc=esc;window.isActive=active;window.activeLabel=v=>active(v)?'YA':'TIDAK';window.money=money;window.msg=msg;window.go=go;window.load=load;window.render=render;window.pmSetCurrentPage=setCurrentPage;window.masterPage=masterPage;window.masterForm=masterForm;window.saveMaster=saveMaster;window.quotationPage=quotationPage;window.templatePage=templatePage;window.saveTemplate=saveTemplate;window.settingsPage=settingsPage;window.fillClient=fillClient;
async function init(){document.querySelectorAll('.nav').forEach(button=>button.addEventListener('click',()=>go(button.dataset.p||'dashboard')));$('#menu')?.addEventListener('click',()=>{$('.sidebar')?.classList.toggle('open')});const x=cfg();if(x.url&&x.key&&window.supabase?.createClient){db=window.supabase.createClient(x.url,x.key);window.db=db;window.__PM_STABLE_DB=db;try{await load();setStatus('Supabase terhubung','ok')}catch(e){console.error('[PM] bootstrap',e);setStatus('Supabase gagal','bad');msg('Gagal membaca database: '+(e.message||e))}}else setStatus('Belum terhubung','warn');render()}
function setStatus(text,type){const el=$('#status');if(el){el.textContent=text;el.className='badge '+type}}
init();
})();
