/* PRI_ERP — Dashboard
 * Reporting renderer only. Uses the same transaction definitions as Finance.
 * Do not add dashboard patch/fix files; extend this module instead.
 */
(function(){
  'use strict';
  if(window.__PM_DASHBOARD_UNIFIED__) return;
  window.__PM_DASHBOARD_UNIFIED__=true;

  const S=v=>String(v??'').trim();
  const N=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;let s=S(v).replace(/[^0-9,.-]/g,'');if(!s)return 0;s=s.replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
  const M=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Math.max(0,Math.round(N(v))));
  const P=v=>N(v).toFixed(1)+'%';
  const E=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const DB=()=>{try{if(typeof db!=='undefined'&&db)return db}catch(_){}return window.db||window.__PM_STABLE_DB||null};

  function css(){
    if(document.getElementById('pmDashboardUnifiedCSS'))return;
    const s=document.createElement('style');s.id='pmDashboardUnifiedCSS';s.textContent=`
      #content.pmcy{--cyan:#00e5ff;--pink:#ff2bd6;--green:#00f5a0;--yellow:#ffd166;--purple:#9b6cff;--red:#ff4d6d;--blue:#4d7cff;max-width:1400px;margin:auto;color:#eaf7ff}
      body:has(#content.pmcy){background:radial-gradient(circle at 80% 0%,rgba(0,229,255,.09),transparent 30%),radial-gradient(circle at 10% 70%,rgba(255,43,214,.06),transparent 30%),#050814}
      body:has(#content.pmcy) .sidebar{background:linear-gradient(180deg,#080d1c,#050914);border-right:1px solid #263250}
      body:has(#content.pmcy) .nav.active{background:linear-gradient(90deg,rgba(0,229,255,.16),rgba(155,108,255,.1));border-left:3px solid var(--cyan);color:#fff}
      body:has(#content.pmcy) header{background:rgba(5,8,20,.94);border-bottom:1px solid #22304c}
      .cyhero,.cycard{background:linear-gradient(145deg,#0d1529,#080d19);border:1px solid #263858;border-radius:15px;box-shadow:0 10px 35px #0004}
      .cyhero{padding:22px;margin-bottom:14px;position:relative;overflow:hidden}.cyhero:after{content:'';position:absolute;width:280px;height:280px;right:-120px;top:-170px;background:radial-gradient(circle,rgba(0,229,255,.22),transparent 68%)}
      .cykick{color:var(--cyan);font-size:10px;font-weight:900;letter-spacing:2px}.cyhero h1{margin:5px 0;color:#f5fcff;font-size:28px;text-shadow:0 0 14px #00e5ff55}.cyhero p{color:#8ea6ca;margin:0}.cybtns{display:flex;gap:8px;margin-top:15px;flex-wrap:wrap}.cybtns button{border:1px solid #294766;border-radius:9px;padding:9px 13px;background:#0b1930;color:#dffaff;font-weight:800;cursor:pointer}.cybtns button:first-child{background:linear-gradient(90deg,#086dff,#00bfff);border:0}
      .cygrid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.cykpi{padding:16px;min-height:104px;position:relative;overflow:hidden}.cykpi:before{content:'';position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--a);box-shadow:0 0 12px var(--a)}.cykpi small{display:block;color:#8fa7ca;font-size:10px;font-weight:900;letter-spacing:1px}.cykpi strong{display:block;color:var(--a);font-size:22px;margin-top:11px;font-variant-numeric:tabular-nums}.cykpi span{display:block;color:#6e84a7;font-size:10px;margin-top:7px}
      .cyrow{display:grid;grid-template-columns:1.8fr 1fr;gap:13px;margin-top:13px}.cybottom{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:13px}.cypanel{padding:16px}.cytitle{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.cytitle b{font-size:13px}.cytitle i{font-style:normal;color:var(--cyan);font-size:9px;border:1px solid #164b5b;border-radius:99px;padding:4px 7px}.legend{display:flex;gap:14px;color:#8fa5c5;font-size:9px;margin-bottom:5px}.dot{display:inline-block;width:7px;height:7px;border-radius:50%;margin-right:4px}
      .chart{height:230px;display:flex;align-items:flex-end;gap:7px;padding:12px 4px 24px;border-top:1px solid #192640;overflow:auto}.month{height:195px;min-width:54px;display:flex;align-items:center;flex-direction:column;justify-content:flex-end}.bars{height:170px;display:flex;align-items:flex-end;gap:3px}.bar{width:15px;border-radius:5px 5px 1px 1px;min-height:0}.rev{background:linear-gradient(#00e5ff,#3575ff);box-shadow:0 0 8px #00e5ff44}.pro{background:linear-gradient(#00f5a0,#008d78);box-shadow:0 0 8px #00f5a044}.month label{font-size:9px;color:#7187aa;margin-top:6px}
      .donut{height:150px;width:150px;margin:18px auto;border-radius:50%;display:grid;place-items:center;position:relative}.donut:after{content:'';position:absolute;width:88px;height:88px;border-radius:50%;background:#090e1a;border:1px solid #263858}.donut b{z-index:2;font-size:11px;text-align:center}.legendlist{display:grid;gap:8px}.legendlist div{display:flex;justify-content:space-between;color:#a6b8d3;font-size:10px}.legendlist b{color:#effaff}
      .rank{display:grid;gap:8px}.rankrow{display:grid;grid-template-columns:20px 1fr auto;gap:8px;align-items:center;font-size:10px}.rankrow em{font-style:normal;color:var(--pink);font-weight:900}.rankrow span{color:#e2edfb;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rankrow strong{color:#a9ffe8}.track{height:4px;background:#142037;border-radius:9px;margin-top:4px;overflow:hidden}.track i{display:block;height:100%;background:linear-gradient(90deg,var(--pink),var(--purple))}
      .paybig{font-size:20px;color:var(--green);font-weight:900}.progress{height:8px;background:#121d31;border-radius:99px;overflow:hidden;margin:9px 0 15px}.progress i{display:block;height:100%;background:linear-gradient(90deg,var(--cyan),var(--green),var(--purple))}.cytable{width:100%;border-collapse:collapse;font-size:10px}.cytable th{color:#6681a9;text-transform:uppercase;font-size:8px;text-align:left;padding:7px;border-bottom:1px solid #263858}.cytable td{padding:8px 7px;border-bottom:1px solid #17243b;color:#cad9eb}.good{color:var(--green)!important}.warn{color:var(--yellow)!important}.danger{color:var(--red)!important}.cyerror{color:#ff9aaa;background:#ff4d6d10;border:1px solid #ff4d6d44;padding:9px;border-radius:8px;font-size:10px}
      @media(max-width:1000px){.cygrid{grid-template-columns:repeat(2,1fr)}.cyrow,.cybottom{grid-template-columns:1fr}}@media(max-width:620px){.cygrid{grid-template-columns:1fr}}
    `;document.head.appendChild(s)
  }

  function shell(){
    const c=document.querySelector('#content');if(!c)return null;css();c.className='pmcy';
    c.innerHTML=`<section class="cyhero"><div class="cykick">PRI_ERP · MANAGEMENT CONTROL</div><h1>Dashboard Analisis Penjualan</h1><p>Penjualan · Profit · Margin · Kas · Piutang · Pipeline</p><div class="cybtns"><button type="button" onclick="go('quotation')">＋ Buat Penawaran</button><button type="button" onclick="go('invoice')">▣ Invoice</button><button type="button" onclick="go('finance')">◈ Laporan Keuangan</button></div></section><div id="cybody"><div class="cycard cypanel" style="text-align:center;padding:35px;color:#8ea6ca">MEMUAT DATA ANALISIS...</div></div>`;return c
  }

  function invoiceFallback(){try{return JSON.parse(localStorage.getItem('PM_INVOICE_FALLBACK')||'{}')||{}}catch(_){return{}}}
  function extrasFor(id){try{const x=JSON.parse(localStorage.getItem('PM_INVOICE_EXTRA_ITEMS')||'{}')||{};return Array.isArray(x[String(id)])?x[String(id)]:[]}catch(_){return[]}}
  function meta(r){const x=invoiceFallback()[String(r.id)]||{};return{no:S(r.nomor_invoice||x.nomor_invoice),status:S(r.status_invoice||x.status_invoice),date:S(r.tanggal_invoice||x.tanggal_invoice)}}
  function sold(r,paid,m){const st=S(r.status).toUpperCase();return !!m.no||!!m.status||!!m.date||paid>0||/DEAL|ACC|APPROVED|DISETUJUI|TERKIRIM|SENT|PUBLISHED|DELIVERED|INVOICE|LUNAS/.test(st)}
  function masterFor(i,ms){const code=S(i.kode||i.kode_item||i.code).toLowerCase(),name=S(i.item||i.nama_item||i.nama||i.name).toLowerCase();return ms.find(x=>S(x.kode||x.kode_item||x.code).toLowerCase()===code)||ms.find(x=>name&&S(x.item||x.nama_item||x.nama||x.name).toLowerCase()===name)||null}
  function unitCost(i,m){const own=N(i.harga_modal??i.modal??i.harga_beli??i.harga_cost);return own>0?own:N(m?.harga_modal??m?.modal??m?.harga_beli??m?.harga_cost)}
  function typeOf(i,m){const sat=S(m?.satuan||i?.satuan).toLowerCase().replace(/\s+/g,'');if(['unit','units','pcs','pc','buah','set'].includes(sat))return'qty';if(['m2','m²','meter2','meterpersegi','luas'].includes(sat))return'luas';const t=(S(m?.item)+' '+S(m?.kategori)+' '+S(m?.kode)+' '+S(i?.item)+' '+S(i?.kategori)).toLowerCase();if(/rigging|rig/.test(t))return'rigging';if(/level/.test(t))return'level';if(/led|videotron/.test(t))return'luas';return'qty'}
  function itemCost(i,m,ss){const unit=unitCost(i,m);if(unit<=0)return 0;const t=typeOf(i,m),rows=ss.filter(s=>String(s.penawaran_item_id??s.item_id)===String(i.id));const calc=s=>{const dur=Math.max(1,N(s?.durasi)||((s?.tanggal_mulai&&s?.tanggal_selesai)?Math.round((new Date(S(s.tanggal_selesai)+'T00:00:00')-new Date(S(s.tanggal_mulai)+'T00:00:00'))/86400000)+1:N(i.durasi)||1)),qty=Math.max(1,N(s?.qty??s?.jumlah??i.qty??i.jumlah??1)),w=N(i.lebar),h=N(i.tinggi),len=N(i.panjang);if(t==='luas')return w*h*unit*dur;if(t==='level')return w*unit*dur;if(t==='rigging')return(len*2+h*2)*unit*dur;return qty*unit*dur};return rows.length?rows.reduce((a,s)=>a+calc(s),0):calc(null)}
  function itemSaleValue(i,ss){const t=S(i?.tipe_perhitungan||i?.tipe||typeOf(i,null)).toLowerCase(),rows=ss.filter(s=>String(s.penawaran_item_id??s.item_id)===String(i.id)),price=N(i?.harga??i?.harga_jual),level=!!i?.level_enabled?N(i?.level_subtotal)||N(i?.lebar)*N(i?.level_harga)*Math.max(1,N(i?.qty??i?.jumlah)||1):0,calc=s=>{const dur=Math.max(1,N(s?.durasi)||N(i?.durasi)||1),qty=Math.max(1,N(s?.qty??i?.qty??i?.jumlah)||1),w=N(i?.lebar),h=N(i?.tinggi),len=N(i?.panjang);const base=t==='luas'?price*w*h*qty*dur:t==='level'?price*w*qty*dur:t==='rigging'?price*((len*2)+(h*2))*qty*dur:price*qty*dur;return Math.max(0,base)};const gross=(rows.length?rows.reduce((a,s)=>a+calc(s),0):calc(null))+level,pct=Math.max(0,Math.min(100,N(i?.diskon_persen))),disc=pct>0?Math.min(gross,Math.round(gross*pct/100)):Math.min(gross,Math.max(0,N(i?.diskon_nominal)));return Math.max(0,gross-disc)}

  async function load(){
    const c=document.querySelector('#cybody'),d=DB();if(!c||!d)return;
    try{
      const [qr,ir,mr,sr,pr]=await Promise.all([d.from('penawaran').select('*').order('id',{ascending:false}),d.from('penawaran_items').select('*').order('id'),d.from('master_harga').select('*').order('id'),d.from('penawaran_jadwal').select('*').order('id'),d.from('pembayaran_penawaran').select('*').order('id')]);
      if(qr.error)throw qr.error;if(ir.error)throw ir.error;if(mr.error)throw mr.error;if(sr.error)throw sr.error;if(pr.error)throw pr.error;
      const qs=qr.data||[],its=ir.data||[],ms=mr.data||[],ss=sr.data||[],ps=pr.data||[],byQ=new Map(),paid=new Map();
      its.forEach(i=>{const k=S(i.penawaran_id);if(!byQ.has(k))byQ.set(k,[]);byQ.get(k).push(i)});ps.forEach(p=>{const k=S(p.penawaran_id);paid.set(k,(paid.get(k)||0)+N(p.nominal))});
      const rows=qs.filter(r=>!/BATAL|CANCEL|DIBATALKAN/i.test(S(r.status))).map(r=>{const qits=byQ.get(S(r.id))||[],details=qits.map(i=>{const m=masterFor(i,ms);return{item:i,cost:itemCost(i,m,ss),master:m}}),subtotal=Math.max(0,N(r.subtotal)||qits.reduce((a,i)=>a+N(i.subtotal),0)),discount=Math.max(0,Math.min(subtotal,N(r.diskon??r.discount??r.discount_amount))),quoteTotal=Math.max(0,N(r.total??r.grand_total??r.total_harga)||subtotal-discount),pay=N(paid.get(S(r.id))),m=meta(r),ex=extrasFor(r.id),extra=ex.reduce((a,x)=>a+N(x.subtotal),0),invoiceTotal=(m.no||m.status||m.date)?quoteTotal+extra:0,isSold=sold(r,pay,m),modal=details.reduce((a,x)=>a+x.cost,0),profit=quoteTotal-modal,margin=quoteTotal?profit/quoteTotal*100:0,balance=invoiceTotal>0?Math.max(0,invoiceTotal-pay):0;return{r,qits,details,subtotal,discount,quoteTotal,pay,m,extra,invoiceTotal,isSold,modal,profit,margin,balance,date:S(r.tanggal_penawaran||r.created_at||r.tanggal_mulai).slice(0,10)}});
      const sales=rows.filter(x=>x.isSold),revenue=sales.reduce((a,x)=>a+x.quoteTotal,0),modal=sales.reduce((a,x)=>a+x.modal,0),profit=sales.reduce((a,x)=>a+x.profit,0),discount=sales.reduce((a,x)=>a+x.discount,0),cash=rows.reduce((a,x)=>a+x.pay,0),invoiceValue=sales.reduce((a,x)=>a+x.invoiceTotal,0),receivable=sales.reduce((a,x)=>a+x.balance,0),pipeline=rows.filter(x=>!x.isSold).reduce((a,x)=>a+x.quoteTotal,0),margin=revenue?profit/revenue*100:0;
      const months=[],now=new Date();for(let z=11;z>=0;z--){const d0=new Date(now.getFullYear(),now.getMonth()-z,1);months.push({k:`${d0.getFullYear()}-${String(d0.getMonth()+1).padStart(2,'0')}`,label:d0.toLocaleDateString('id-ID',{month:'short'}),sales:0,profit:0})}const byMonth=new Map(months.map(x=>[x.k,x]));sales.forEach(x=>{const z=byMonth.get(x.date.slice(0,7));if(z){z.sales+=x.quoteTotal;z.profit+=x.profit}});
      const status={pipeline:rows.filter(x=>!x.isSold).length,draft:rows.filter(x=>x.isSold&&S(x.m.status).toUpperCase()==='DRAFT'&&x.pay<=0).length,invoice:sales.filter(x=>x.m.no||x.m.status||x.m.date).length,lunas:sales.filter(x=>x.invoiceTotal>0&&x.balance<=0).length};
      const topMap=new Map();sales.forEach(x=>x.qits.forEach(i=>{const key=S(i.kode||i.item||i.nama_item)||'ITEM';const name=S(i.item||i.nama_item||i.kode)||'Item';topMap.set(key,{name,value:(topMap.get(key)?.value||0)+itemSaleValue(i,ss)});}));const top=[...topMap.values()].sort((a,b)=>b.value-a.value).slice(0,8),topMax=Math.max(1,...top.map(x=>x.value)),mx=Math.max(1,...months.map(x=>Math.max(x.sales,x.profit))),paidPct=revenue?Math.min(100,cash/revenue*100):0;
      const donutTotal=Math.max(1,status.pipeline+status.invoice+status.lunas),a=status.pipeline/donutTotal*360,b=(status.invoice/donutTotal*360),c2=status.lunas/donutTotal*360;
      c.innerHTML=`<div class="cygrid"><div class="cycard cykpi" style="--a:var(--cyan)"><small>Penjualan Bersih</small><strong>${M(revenue)}</strong><span>${sales.length} transaksi terjual</span></div><div class="cycard cykpi" style="--a:var(--green)"><small>Laba Kotor</small><strong>${M(profit)}</strong><span>margin ${P(margin)}</span></div><div class="cycard cykpi" style="--a:var(--pink)"><small>Kas Masuk</small><strong>${M(cash)}</strong><span>semua pembayaran</span></div><div class="cycard cykpi" style="--a:var(--yellow)"><small>Piutang</small><strong>${M(receivable)}</strong><span>${sales.filter(x=>x.balance>0).length} invoice belum lunas</span></div><div class="cycard cykpi" style="--a:var(--purple)"><small>Total Modal</small><strong>${M(modal)}</strong><span>harga modal item</span></div><div class="cycard cykpi" style="--a:${margin>=20?'var(--green)':'var(--red)'}"><small>Margin Kotor</small><strong>${P(margin)}</strong><span>target internal ≥ 20%</span></div><div class="cycard cykpi" style="--a:var(--cyan)"><small>Diskon</small><strong>${M(discount)}</strong><span>penawaran terjual</span></div><div class="cycard cykpi" style="--a:var(--purple)"><small>Pipeline</small><strong>${M(pipeline)}</strong><span>${status.pipeline} transaksi belum terjual</span></div></div>
      <div class="cyrow"><section class="cycard cypanel"><div class="cytitle"><b>Penjualan vs Profit · 12 Bulan</b><i>UNIFIED DATA</i></div><div class="legend"><span><i class="dot" style="background:var(--cyan)"></i>Penjualan</span><span><i class="dot" style="background:var(--green)"></i>Profit</span></div><div class="chart">${months.map(x=>`<div class="month"><div class="bars"><div class="bar rev" style="height:${x.sales?Math.max(4,x.sales/mx*160):0}px" title="Penjualan ${M(x.sales)}"></div><div class="bar pro" style="height:${x.profit?Math.max(4,Math.max(0,x.profit)/mx*160):0}px" title="Profit ${M(x.profit)}"></div></div><label>${E(x.label)}</label></div>`).join('')}</div></section><section class="cycard cypanel"><div class="cytitle"><b>Status Transaksi</b><i>LIVE</i></div><div class="donut" style="background:conic-gradient(var(--yellow) 0deg ${a}deg,var(--cyan) ${a}deg ${a+b}deg,var(--green) ${a+b}deg 360deg)"><b>${sales.length}<br>TERJUAL</b></div><div class="legendlist"><div><span>Pipeline</span><b>${status.pipeline}</b></div><div><span>Invoice</span><b>${status.invoice}</b></div><div><span>Lunas</span><b class="good">${status.lunas}</b></div></div></section></div>
      <div class="cybottom"><section class="cycard cypanel"><div class="cytitle"><b>Top Produk / Jasa</b><i>TOP 8</i></div><div class="rank">${top.map((x,i)=>`<div><div class="rankrow"><em>${String(i+1).padStart(2,'0')}</em><span>${E(x.name)}</span><strong>${M(x.value)}</strong></div><div class="track"><i style="width:${x.value/topMax*100}%"></i></div></div>`).join('')||'<div style="color:#7388a9">Belum ada item.</div>'}</div></section><section class="cycard cypanel"><div class="cytitle"><b>Highlight Pembukuan</b><i>FINANCE</i></div><div class="paybox"><span style="color:#8ea5c7;font-size:12px">Cash Collection</span><div class="paybig">${M(cash)}</div><div class="progress"><i style="width:${paidPct}%"></i></div><span style="color:#7f96b8;font-size:10px">${paidPct.toFixed(1)}% dari penjualan bersih</span><div class="cygrid" style="grid-template-columns:1fr 1fr;gap:10px;margin-top:15px"><div><span style="color:#7389aa;font-size:10px">Laba Kotor</span><div style="color:var(--green);font-weight:900">${M(profit)}</div></div><div><span style="color:#7389aa;font-size:10px">Piutang</span><div class="${receivable>0?'warn':'good'}" style="font-weight:900">${M(receivable)}</div></div><div><span style="color:#7389aa;font-size:10px">Invoice</span><div style="color:#cfe2fb;font-weight:900">${M(invoiceValue)}</div></div><div><span style="color:#7389aa;font-size:10px">Diskon</span><div style="color:var(--cyan);font-weight:900">${M(discount)}</div></div></div></div></section></div>`;
    }catch(e){console.error('[PM] dashboard unified',e);c.innerHTML=`<div class="cycard cypanel cyerror">Gagal membaca Dashboard: ${E(e.message||e)}</div>`}
  }

  async function render(){shell();await load()}
  window.pmRenderDashboardCyber=render;
})();