/* Priangan Multimedia — history / edit / publish / delete / discount */
(function(){
'use strict';
const S=v=>String(v??'').trim(),N=v=>{const n=Number(S(v).replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));return Number.isFinite(n)?n:0},E=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),M=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(N(v)),D=(a,b)=>{if(!a||!b)return 1;const d=Math.round((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/86400000);return d>=0?d+1:1},toast=t=>typeof window.msg==='function'?window.msg(t):alert(t);
let editId=null,editNo='',discount=0,discountPct=0;
function DB(){if(typeof db!=='undefined'&&db)return db;const c=window.PRIANGAN_CONFIG||{},u=S(localStorage.getItem('SUPABASE_URL')||c.SUPABASE_URL),k=S(localStorage.getItem('SUPABASE_ANON_KEY')||c.SUPABASE_ANON_KEY);return u&&k&&window.supabase?.createClient?window.supabase.createClient(u,k):null}
function quoteDate(row){return S(row.tanggal_penawaran||row.tanggal||row.created_at||row.tanggal_mulai||'').slice(0,10)}
function sub(i){const h=N(i.harga??i.harga_jual),d=D(i.mulai??i.tanggal_mulai,i.selesai??i.tanggal_selesai),w=N(i.lebar),t=N(i.tinggi),p=N(i.panjang),q=Math.max(1,N(i.qty??i.jumlah));if(i.tipe==='level')return w*h*d;if(i.tipe==='luas')return w*t*h*d;if(i.tipe==='rigging')return((p*2)+(t*2))*h*d;return q*h*d}
function base(){return(window.items||[]).reduce((s,i)=>s+sub(i),0)}
function discountUI(){const total=document.querySelector('#total');if(!total||document.querySelector('#pmDiscount'))return;const card=total.closest('.card');if(!card)return;const box=document.createElement('div');box.id='pmDiscount';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid var(--border)';box.innerHTML=`<div class="grid g2"><div class="field"><label>Diskon (%)</label><input id="pmDiscPct" type="number" min="0" max="100" step="0.01" value="${discountPct.toFixed(2)}"></div><div class="field"><label>Diskon (Rp)</label><input id="pmDisc" type="number" min="0" step="1" value="${Math.round(discount)}"></div></div><div class="sum" style="margin-top:10px"><span>Grand Total</span><b id="pmGrand">${M(Math.max(0,base()-discount))}</b></div>`;card.insertBefore(box,total.closest('.sum'));const pct=box.querySelector('#pmDiscPct'),amt=box.querySelector('#pmDisc');const sync=who=>{const b=base();if(who==='pct'){discountPct=Math.max(0,Math.min(100,N(pct.value)));discount=Math.round(b*discountPct/100);amt.value=discount}else{discount=Math.max(0,Math.min(b,N(amt.value)));discountPct=b?discount/b*100:0;pct.value=discountPct.toFixed(2)}box.querySelector('#pmGrand').textContent=M(Math.max(0,b-discount));total.textContent=M(b)};pct.oninput=()=>sync('pct');amt.oninput=()=>sync('amt');sync('amt')}
async function editQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');try{const q=await d.from('penawaran').select('*').eq('id',id).single();if(q.error)throw q.error;const r=await d.from('penawaran_items').select('*').eq('penawaran_id',id).order('id');if(r.error)throw r.error;const row=q.data,its=r.data||[],b=its.reduce((s,x)=>s+N(x.subtotal),0),net=N(row.grand_total??row.total);editId=id;editNo=S(row.nomor_penawaran||row.nomor);discount=Math.max(0,Math.min(b,b-net));if(row.diskon!=null)discount=Math.min(b,N(row.diskon));discountPct=b?discount/b*100:0;window.items=its.map(x=>({id:Date.now()+Math.random(),kode:S(x.kode),item:S(x.item||x.nama_item),harga:N(x.harga_jual??x.harga),qty:N(x.qty)||1,lebar:N(x.lebar),tinggi:N(x.tinggi),panjang:N(x.panjang),mulai:S(x.tanggal_mulai),selesai:S(x.tanggal_selesai),tipe:S(x.tipe_perhitungan)||'qty'}));if(typeof window.go==='function')window.go('quotation');else{window.page='quotation';if(typeof window.render==='function')window.render()}setTimeout(()=>{const set=(s,v)=>{const e=document.querySelector(s);if(e)e.value=v??''};set('#qc',row.nama_client);set('#qp',row.perusahaan);set('#qw',row.whatsapp||row.telepon);set('#qe',row.email);set('#qeve',row.nama_event||row.event_name||row.event||row.project);set('#qs',row.tanggal_mulai);set('#qe2',row.tanggal_selesai);discountUI();const a=document.querySelector('#pmDisc');if(a){a.value=Math.round(discount);a.dispatchEvent(new Event('input'))}toast('Mode edit: '+(editNo||id))},50)}catch(e){console.error(e);toast('Gagal membuka penawaran: '+(e.message||e))}}
async function publishQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');const r=await d.from('penawaran').update({status:'TERKIRIM'}).eq('id',id);if(r.error){console.error(r.error);return toast('Gagal publish: '+r.error.message)}toast('Penawaran ditandai SUDAH DIBERIKAN.');await renderHistory()}
async function deleteQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');if(!confirm('Hapus penawaran ini beserta item dan jadwalnya?'))return;try{const old=await d.from('penawaran_items').select('id').eq('penawaran_id',id);if(old.error)throw old.error;for(const x of old.data||[]){const j=await d.from('penawaran_jadwal').delete().eq('item_id',x.id);if(j.error)throw j.error}let r=await d.from('penawaran_items').delete().eq('penawaran_id',id);if(r.error)throw r.error;r=await d.from('penawaran').delete().eq('id',id);if(r.error)throw r.error;toast('Penawaran berhasil dihapus.');await renderHistory()}catch(e){console.error(e);toast('Gagal menghapus penawaran: '+e.message)}}
async function renderHistory(){const d=DB();if(!d)return;const r=await d.from('penawaran').select('*').order('id',{ascending:false});if(r.error){console.error(r.error);return toast('Gagal membaca riwayat: '+r.error.message)}const c=document.querySelector('#content');if(!c)return;const rows=r.data||[];c.innerHTML=`<div class="head"><div><h1>Riwayat Penawaran</h1><p>Penawaran tersimpan di Supabase.</p></div><button class="btn" onclick="go('quotation')">+ Buat Penawaran</button></div><div class="card"><div class="scroll"><table class="table pm-history-table"><thead><tr><th>No</th><th>Tanggal</th><th>Client</th><th>Perusahaan</th><th>Event</th><th>DP</th><th>Dibayar</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(row=>{const status=S(row.status||'DRAFT').toUpperCase(),sent=['TERKIRIM','PUBLISHED','SENT'].includes(status);return `<tr><td>${E(row.nomor_penawaran||row.nomor||'-')}</td><td>${E(quoteDate(row)||'-')}</td><td>${E(row.nama_client||'-')}</td><td>${E(row.perusahaan||'-')}</td><td>${E(row.nama_event||row.event_name||row.event||row.project||'-')}</td><td class="pm-pay-dp">Rp 0</td><td class="pm-pay-paid">Rp 0</td><td>${M(row.grand_total??row.total)}</td><td><span class="pm-status ${sent?'sent':'draft'}">${E(sent?'TERKIRIM':status)}</span></td><td><div class="pmHistActions"><div class="pmActionRow pmActionRowTop"><button class="btn sm" onclick="editQuotation(${Number(row.id)})">Edit</button>${sent?'<span class="pm-sent-note">Sudah diberikan</span>':`<button class="btn green sm" onclick="publishQuotation(${Number(row.id)})">Publish</button>`}<button class="btn red sm" onclick="deleteQuotation(${Number(row.id)})">Hapus</button></div><div class="pmActionRow pmActionRowBottom"><button type="button" class="btn secondary sm" onclick="inputDP(${Number(row.id)})">DP</button><button type="button" class="btn green sm" onclick="inputPelunasan(${Number(row.id)})">Bayar</button></div></div></td></tr>`}).join('')||'<tr><td colspan="10">Belum ada penawaran.</td></tr>'}</tbody></table></div></div>`}
window.editQuotation=editQuote;window.publishQuotation=publishQuote;window.deleteQuotation=deleteQuote;window.renderHistory=renderHistory;
const style=document.createElement('style');style.textContent=`.pm-history-table th,.pm-history-table td{vertical-align:middle}.pm-history-table th:last-child,.pm-history-table td:last-child{min-width:190px}.pmHistActions{display:flex!important;flex-direction:column!important;align-items:flex-start!important;gap:6px!important;min-width:0!important}.pmActionRow{display:flex!important;align-items:center!important;gap:5px!important;flex-wrap:wrap!important}.pmActionRow .btn{white-space:nowrap!important}.pm-sent-note{font-size:11px;white-space:nowrap;color:#7dd3fc}.pm-pay-dp,.pm-pay-paid{white-space:nowrap}.pm-history-table .btn.sm{padding:6px 9px;font-size:12px}@media(max-width:1100px){.pm-history-table{min-width:1100px}}`;document.head.appendChild(style);
const observer=new MutationObserver(()=>{if(document.querySelector('#total'))discountUI();if(S(document.querySelector('#title')?.textContent)==='Riwayat Penawaran'&&!document.querySelector('.pm-history-table'))renderHistory()});observer.observe(document.body,{childList:true,subtree:true})
})();
