/* Priangan Multimedia — history / edit / publish / delete / discount */
(function(){
'use strict';
const S=v=>String(v??'').trim(),N=v=>{const n=Number(S(v).replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));return Number.isFinite(n)?n:0},E=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const M=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(N(v));
const D=(a,b)=>{if(!a||!b)return 1;const d=Math.round((new Date(b+'T00:00:00')-new Date(a+'T00:00:00'))/86400000);return d>=0?d+1:1};
const toast=t=>typeof window.msg==='function'?window.msg(t):alert(t);
let editId=null,editNo='',discount=0,discountPct=0;
function DB(){if(typeof db!=='undefined'&&db)return db;const c=window.PRIANGAN_CONFIG||{},u=S(localStorage.getItem('SUPABASE_URL')||c.SUPABASE_URL),k=S(localStorage.getItem('SUPABASE_ANON_KEY')||c.SUPABASE_ANON_KEY);return u&&k&&window.supabase?.createClient?window.supabase.createClient(u,k):null}
function quoteDate(row){return S(row.tanggal_penawaran||row.tanggal||row.created_at||row.tanggal_mulai||'').slice(0,10)}
function getItems(){
  if(Array.isArray(window.items))return window.items;
  if(Array.isArray(window.__pmItems))return window.__pmItems;
  const cards=[...document.querySelectorAll('#items > .item')];
  return cards.map(card=>{
    const fields=[...card.querySelectorAll('.field')];
    const val=label=>{const f=fields.find(x=>S(x.querySelector('label')?.textContent).toLowerCase().includes(label.toLowerCase()));return f?.querySelector('input,select,textarea')?.value||''};
    const opt=card.querySelector('select')?.selectedOptions?.[0];
    const raw=S(opt?.textContent),m=raw.match(/^\[([^\]]+)\]\s*(.*)$/),kode=S(card.querySelector('select')?.value)||S(m?.[1]);
    return {kode,item:S(m?.[2]||raw),harga:N(val('Harga Jual')),qty:Math.max(1,N(val('Jumlah (Qty)'))||1),lebar:N(val('Lebar Videotron')||val('Lebar Level')),tinggi:N(val('Tinggi Videotron')||val('Tinggi Level')||val('Tinggi')),panjang:N(val('Panjang Rigging')),mulai:S(val('Tanggal Mulai')),selesai:S(val('Tanggal Selesai')),tipe:S(val('Tipe Perhitungan')).toLowerCase()||'qty'};
  }).filter(x=>x.kode&&x.item);
}
function sub(i){const h=N(i.harga??i.harga_jual),d=D(i.mulai??i.tanggal_mulai,i.selesai??i.tanggal_selesai),w=N(i.lebar),t=N(i.tinggi),p=N(i.panjang),q=Math.max(1,N(i.qty??i.jumlah));if(i.tipe==='level')return w*h*d;if(i.tipe==='luas')return w*t*h*d;if(i.tipe==='rigging')return((p*2)+(t*2))*h*d;return q*h*d}
function base(){return getItems().reduce((s,i)=>s+sub(i),0)}
function discountUI(){const total=document.querySelector('#total');if(!total||document.querySelector('#pmDiscount'))return;const card=total.closest('.card');if(!card)return;const box=document.createElement('div');box.id='pmDiscount';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid var(--border)';box.innerHTML=`<div class="grid g2"><div class="field"><label>Diskon (%)</label><input id="pmDiscPct" type="number" min="0" max="100" step="0.01" value="${discountPct.toFixed(2)}"></div><div class="field"><label>Diskon (Rp)</label><input id="pmDisc" type="number" min="0" step="1" value="${Math.round(discount)}"></div></div><div class="sum" style="margin-top:10px"><span>Grand Total</span><b id="pmGrand">${M(Math.max(0,base()-discount))}</b></div>`;card.insertBefore(box,total.closest('.sum'));const pct=box.querySelector('#pmDiscPct'),amt=box.querySelector('#pmDisc');const sync=who=>{const b=base();if(who==='pct'){discountPct=Math.max(0,Math.min(100,N(pct.value)));discount=Math.round(b*discountPct/100);amt.value=discount}else{discount=Math.max(0,Math.min(b,N(amt.value)));discountPct=b?discount/b*100:0;pct.value=discountPct.toFixed(2)}box.querySelector('#pmGrand').textContent=M(Math.max(0,b-discount));total.textContent=M(Math.max(0,b-discount));window.__pmDiscountValue=discount;window.__pmDiscountPct=discountPct;window.__pmDiscountBase=b;window.__pmNetTotal=Math.max(0,b-discount)};pct.oninput=()=>sync('pct');amt.oninput=()=>sync('amt');sync('amt')}
async function editQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');try{const q=await d.from('penawaran').select('*').eq('id',id).single();if(q.error)throw q.error;const r=await d.from('penawaran_items').select('*').eq('penawaran_id',id).order('id');if(r.error)throw r.error;const row=q.data,its=r.data||[],b=its.reduce((s,x)=>s+N(x.subtotal),0),net=N(row.grand_total??row.total);editId=id;editNo=S(row.nomor_penawaran||row.nomor);discount=Math.max(0,Math.min(b,b-net));if(row.diskon!=null)discount=Math.min(b,N(row.diskon));discountPct=b?discount/b*100:0;window.items=its.map(x=>({id:Date.now()+Math.random(),kode:S(x.kode),item:S(x.item||x.nama_item),harga:N(x.harga_jual??x.harga),qty:N(x.qty)||1,lebar:N(x.lebar),tinggi:N(x.tinggi),panjang:N(x.panjang),mulai:S(x.tanggal_mulai),selesai:S(x.tanggal_selesai),tipe:S(x.tipe_perhitungan)||'qty'}));window.__pmItems=window.items;if(typeof window.go==='function')window.go('quotation');else{window.page='quotation';if(typeof window.render==='function')window.render()}setTimeout(()=>{const set=(s,v)=>{const e=document.querySelector(s);if(e)e.value=v??''};set('#qc',row.nama_client);set('#qp',row.perusahaan);set('#qw',row.whatsapp||row.telepon);set('#qe',row.email);set('#qeve',row.nama_event||row.event_name||row.event||row.project);set('#qs',row.tanggal_mulai);set('#qe2',row.tanggal_selesai);discountUI();const a=document.querySelector('#pmDisc');if(a){a.value=Math.round(discount);a.dispatchEvent(new Event('input'))}toast('Mode edit: '+(editNo||id))},50)}catch(e){console.error(e);toast('Gagal membuka penawaran: '+(e.message||e))}}
async function publishQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');const r=await d.from('penawaran').update({status:'TERKIRIM'}).eq('id',id);if(r.error){console.error(r.error);return toast('Gagal publish: '+r.error.message)}toast('Penawaran ditandai SUDAH DIBERIKAN.');await renderHistory()}
async function deleteQuote(id){const d=DB();if(!d)return toast('Supabase belum terhubung.');if(!confirm('Hapus penawaran ini beserta item dan jadwalnya?'))return;try{const old=await d.from('penawaran_items').select('id').eq('penawaran_id',id);if(old.error)throw old.error;for(const x of old.data||[]){const j=await d.from('penawaran_jadwal').delete().eq('item_id',x.id);if(j.error)throw j.error}let r=await d.from('penawaran_items').delete().eq('penawaran_id',id);if(r.error)throw r.error;r=await d.from('penawaran').delete().eq('id',id);if(r.error)throw r.error;toast('Penawaran berhasil dihapus.');await renderHistory()}catch(e){console.error(e);toast('Gagal menghapus penawaran: '+e.message)}}
function actionRow(row,sent){const id=Number(row.id);return `<tr class="pmActionDataRow"><td colspan="9" class="pmHistoryActionCell"><div class="pmHistoryActions"><button type="button" class="btn sm" onclick="editQuotation(${id})">Edit</button>${sent?'<span class="pm-sent-note">Sudah diberikan</span>':'<button type="button" class="btn green sm" onclick="publishQuotation('+id+')">Publish</button>'}<button type="button" class="btn secondary sm" onclick="inputDP(${id})">DP</button><button type="button" class="btn red sm" onclick="deleteQuotation(${id})">Hapus</button></div></td></tr>`}
async function renderHistory(){const d=DB();if(!d)return;const r=await d.from('penawaran').select('*').order('id',{ascending:false});if(r.error){console.error(r.error);return toast('Gagal membaca riwayat: '+r.error.message)}const c=document.querySelector('#content');if(!c)return;const rows=r.data||[];const htmlRows=rows.map(row=>{const status=S(row.status||'DRAFT').toUpperCase(),sent=['TERKIRIM','PUBLISHED','SENT'].includes(status);return `<tr class="pmQuoteDataRow"><td>${E(row.nomor_penawaran||row.nomor||'-')}</td><td>${E(quoteDate(row)||'-')}</td><td>${E(row.nama_client||'-')}</td><td>${E(row.perusahaan||'-')}</td><td>${E(row.nama_event||row.event_name||row.event||row.project||'-')}</td><td class="pm-pay-dp">Rp 0</td><td class="pm-pay-paid">Rp 0</td><td>${M(row.grand_total??row.total)}</td><td><span class="pm-status ${sent?'sent':'draft'}">${E(sent?'TERKIRIM':status)}</span></td></tr>${actionRow(row,sent)}`}).join('');c.innerHTML=`<div class="head"><div><h1>Riwayat Penawaran</h1><p>Penawaran tersimpan di Supabase.</p></div><button class="btn" onclick="go('quotation')">+ Buat Penawaran</button></div><div class="card"><div class="scroll"><table class="table pm-history-table"><thead><tr><th>No</th><th>Tanggal</th><th>Client</th><th>Perusahaan</th><th>Event</th><th>DP</th><th>Dibayar</th><th>Total</th><th>Status</th></tr></thead><tbody>${htmlRows}</tbody></table></div></div>`}
window.editQuotation=editQuote;window.publishQuotation=publishQuote;window.deleteQuotation=deleteQuote;window.renderHistory=renderHistory;
const style=document.createElement('style');style.textContent=`.pm-history-table{width:100%;table-layout:auto}.pm-history-table th,.pm-history-table td{vertical-align:middle}.pm-history-table .pmQuoteDataRow td{border-bottom:0!important}.pm-history-table .pmActionDataRow td.pmHistoryActionCell{padding:7px 10px 10px!important;border-top:0!important;border-bottom:1px solid var(--border)!important;background:rgba(30,41,59,.28)!important}.pmHistoryActions{display:flex!important;flex-direction:row!important;align-items:center!important;justify-content:flex-start!important;gap:6px!important;flex-wrap:wrap!important;width:100%!important}.pmHistoryActions .btn.sm{padding:6px 10px!important;font-size:12px!important;line-height:1!important;margin:0!important;white-space:nowrap!important}.pm-sent-note{font-size:11px!important;white-space:nowrap!important;color:#7dd3fc!important;padding:6px 4px!important}.pm-pay-dp,.pm-pay-paid{white-space:nowrap}@media(max-width:1100px){.pm-history-table{min-width:900px!important}}`;document.head.appendChild(style);
/* Deliberately no global MutationObserver here. History rendering is handled by the runtime history route, and the discount UI is initialized explicitly by quotation/edit flows. */
})();
