/* Priangan Multimedia — Invoice Domain Core
 * Single invoice authority.
 * Invoice metadata and extra items live only in Supabase.
 * Payments live in pembayaran_penawaran.
 * localStorage is intentionally not used as a financial data source.
 */
(function(){
'use strict';
if(window.__PM_INVOICE_DOMAIN_CORE)return;window.__PM_INVOICE_DOMAIN_CORE=true;
const S=v=>String(v??'').trim();
const N=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const s=S(v).replace(/[^0-9,.-]/g,'');if(!s)return 0;const n=Number(s.replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'));return Number.isFinite(n)?n:0};
const M=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Math.max(0,Math.round(N(v))));
const E=v=>S(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const D=v=>{if(!v)return'-';const x=new Date(S(v).slice(0,10)+'T00:00:00');return Number.isNaN(x.getTime())?E(v):x.toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'})};
const msg=t=>typeof window.msg==='function'?window.msg(t):console.warn('[PM]',t);
const DB=()=>window.db||window.__PM_STABLE_DB||null;
const days=(a,b)=>{if(!a||!b)return 1;const d=Math.round((new Date(S(b)+'T00:00:00')-new Date(S(a)+'T00:00:00'))/86400000);return d>=0?d+1:1};
let current=null;

async function loadData(){
 const d=DB();if(!d)throw Error('Supabase belum terhubung.');
 const [q,p,x]=await Promise.all([d.from('penawaran').select('*').order('id',{ascending:false}),d.from('pembayaran_penawaran').select('*').order('id',{ascending:true}),d.from('penawaran_invoice_items').select('*').order('id',{ascending:true})]);
 if(q.error)throw q.error;if(p.error)throw p.error;if(x.error)throw x.error;
 const paid=new Map(),extras=new Map();(p.data||[]).forEach(r=>paid.set(String(r.penawaran_id),(paid.get(String(r.penawaran_id))||0)+N(r.nominal)));(x.data||[]).forEach(r=>{const k=String(r.penawaran_id);if(!extras.has(k))extras.set(k,[]);extras.get(k).push(r)});
 return{quotes:q.data||[],payments:p.data||[],extras};
}
function quoteTotal(q){return Math.max(0,N(q?.grand_total??q?.total))}
function paymentTotal(payments,id){return (payments||[]).filter(x=>String(x.penawaran_id)===String(id)).reduce((a,x)=>a+N(x.nominal),0)}
function extraTotal(extras){return (extras||[]).reduce((a,x)=>a+N(x.subtotal),0)}
function invoiceExists(q){return !!S(q.nomor_invoice)}
function invoiceTotal(q,ex){return quoteTotal(q)+extraTotal(ex)}
function statusText(q,paid,total){if(q.status_invoice==='DIBATALKAN')return'DIBATALKAN';if(invoiceExists(q)&&paid>=total&&total>0)return'LUNAS';if(invoiceExists(q))return S(q.status_invoice||'DITERBITKAN');return'BELUM DIBUAT'}

async function invoicePage(){
 const c=document.querySelector('#content');if(!c)return;document.querySelector('#title').textContent='Invoice';c.innerHTML='<div class="card"><div class="empty">Memuat invoice dari Supabase...</div></div>';
 try{const data=await loadData();window.__PM_INVOICE_CACHE=data;const rows=data.quotes.map(q=>{const ex=data.extras.get(String(q.id))||[],paid=paymentTotal(data.payments,q.id),total=invoiceTotal(q,ex),balance=Math.max(0,total-paid);return{q,ex,paid,total,balance,status:statusText(q,paid,total)}});c.innerHTML=`<div class="head"><div><h1>Invoice</h1><p>Sumber data invoice: Supabase. Tidak ada metadata invoice yang disimpan di browser.</p></div><button class="btn secondary" id="pmInvoiceRefresh">↻ Refresh</button></div><div class="card"><div class="scroll"><table class="table"><thead><tr><th>No. Invoice</th><th>Penawaran</th><th>Client</th><th>Event</th><th>Total</th><th>Dibayar</th><th>Sisa</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${E(x.q.nomor_invoice||'-')}</strong>${x.q.jatuh_tempo?`<div class="muted">Tempo ${D(x.q.jatuh_tempo)}</div>`:''}</td><td>${E(x.q.nomor_penawaran||'-')}</td><td>${E(x.q.nama_client||'-')}<div class="muted">${E(x.q.perusahaan||'')}</div></td><td>${E(x.q.nama_event||x.q.event_name||x.q.event||'-')}</td><td>${M(x.total)}${x.ex.length?`<div class="muted">Tambahan ${M(extraTotal(x.ex))}</div>`:''}</td><td>${M(x.paid)}</td><td>${M(x.balance)}</td><td>${E(x.status)}</td><td><div class="actions"><button class="btn sm" type="button" data-inv-edit="${Number(x.q.id)}">${invoiceExists(x.q)?'Edit / Lihat':'Buat Invoice'}</button>${x.balance>0?`<button class="btn sm secondary" type="button" data-inv-pay="${Number(x.q.id)}">${x.paid?'Pelunasan':'Input DP'}</button>`:''}${invoiceExists(x.q)?`<button class="btn sm green" type="button" data-inv-preview="${Number(x.q.id)}">Preview Invoice</button>`:''}</div></td></tr>`).join('')||'<tr><td colspan="9" class="empty">Belum ada penawaran.</td></tr>'}</tbody></table></div></div>`;c.querySelector('#pmInvoiceRefresh').onclick=invoicePage;c.querySelectorAll('[data-inv-edit]').forEach(b=>b.onclick=()=>openForm(Number(b.dataset.invEdit)));c.querySelectorAll('[data-inv-pay]').forEach(b=>b.onclick=()=>inputPayment(Number(b.dataset.invPay)));c.querySelectorAll('[data-inv-preview]').forEach(b=>b.onclick=()=>previewForId(Number(b.dataset.invPreview)));}catch(e){console.error('[PM] invoice page',e);c.innerHTML=`<div class="card"><div class="empty">Gagal membaca invoice: ${E(e.message||e)}</div></div>`}}

async function openForm(id){
 const data=window.__PM_INVOICE_CACHE||await loadData(),q=(data.quotes||[]).find(x=>Number(x.id)===Number(id));if(!q)return msg('Penawaran tidak ditemukan.');const ex=data.extras.get(String(id))||[];const paid=paymentTotal(data.payments,id),total=invoiceTotal(q,ex);current={id,q,extras:ex.map(x=>({...x}))};
 let items=[];const d=DB();const ir=await d.from('penawaran_items').select('*').eq('penawaran_id',id).order('id');if(ir.error)return msg('Gagal membaca item penawaran: '+ir.error.message);items=ir.data||[];
 document.querySelector('#content').innerHTML=`<div class="head"><div><h1>${invoiceExists(q)?'Edit Invoice':'Buat Invoice'}</h1><p>${E(q.nomor_penawaran||'-')} • ${E(q.nama_event||q.event_name||'-')}</p></div><button class="btn secondary" type="button" onclick="invoicePage()">Kembali</button></div>
 <div class="card"><div class="grid g2"><div class="field"><label>No. Invoice</label><input id="invNo" value="${E(q.nomor_invoice||'Otomatis saat simpan')}" readonly></div><div class="field"><label>Tanggal Invoice</label><input id="invDate" type="date" value="${E(q.tanggal_invoice||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Jatuh Tempo</label><input id="invDue" type="date" value="${E(q.jatuh_tempo||q.tanggal_selesai||q.tanggal_mulai||new Date().toISOString().slice(0,10))}"></div><div class="field"><label>Status Invoice</label><select id="invStatus"><option ${q.status_invoice==='DRAFT'?'selected':''}>DRAFT</option><option ${q.status_invoice==='DITERBITKAN'?'selected':''}>DITERBITKAN</option><option ${q.status_invoice==='LUNAS'?'selected':''}>LUNAS</option><option ${q.status_invoice==='DIBATALKAN'?'selected':''}>DIBATALKAN</option></select></div></div></div>
 <div class="card" style="margin-top:16px"><b>Referensi Penawaran</b><div class="grid g2" style="margin-top:12px"><div class="field"><label>Client</label><input value="${E(q.nama_client||'-')}" readonly></div><div class="field"><label>Perusahaan</label><input value="${E(q.perusahaan||'-')}" readonly></div><div class="field"><label>Event / Project</label><input value="${E(q.nama_event||q.event_name||q.event||'-')}" readonly></div><div class="field"><label>No. Penawaran</label><input value="${E(q.nomor_penawaran||'-')}" readonly></div></div></div>
 <div class="card" style="margin-top:16px"><b>Item dari Penawaran</b><div class="scroll" style="margin-top:12px"><table class="table"><thead><tr><th>Kode</th><th>Item</th><th>Qty</th><th>Harga</th><th>Subtotal</th></tr></thead><tbody>${items.map(i=>`<tr><td>${E(i.kode||'-')}</td><td>${E(i.item||i.nama_item||'-')}</td><td>${N(i.qty)||1}</td><td>${M(i.harga??i.harga_jual)}</td><td>${M(i.subtotal)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Tidak ada item.</td></tr>'}</tbody></table></div></div>
 <div class="card" style="margin-top:16px"><div class="actions" style="justify-content:space-between"><b>Item Tambahan Invoice</b><div class="actions"><button class="btn sm" type="button" onclick="invoiceAddItem()">+ Tambah Item</button><button class="btn sm secondary" type="button" onclick="invoiceAddOvertime()">+ Overtime</button></div></div><div id="invoiceExtras" style="margin-top:12px"></div></div>
 <div class="card" style="margin-top:16px"><div class="grid g2"><div class="field"><label>Catatan Invoice</label><textarea id="invNotes" rows="4">${E(q.catatan_invoice||'')}</textarea></div><div><div class="sum"><span>Total Penawaran</span><b>${M(quoteTotal(q))}</b></div><div class="sum" style="margin-top:8px"><span>Tambahan</span><b id="invExtraTotal">${M(extraTotal(ex))}</b></div><div class="sum" style="margin-top:8px"><span>Total Invoice</span><b id="invTotal">${M(total)}</b></div><div class="sum" style="margin-top:8px"><span>Sudah Dibayar</span><b>${M(paid)}</b></div><div class="sum" style="margin-top:8px"><span>Sisa</span><b id="invBalance">${M(Math.max(0,total-paid))}</b></div></div></div></div>
 <div class="actions" style="margin-top:16px"><button class="btn secondary" type="button" onclick="invoicePage()">Batal</button><button class="btn green" type="button" onclick="saveInvoice()">Simpan Invoice</button><button class="btn" type="button" onclick="previewInvoice()">Preview / Cetak</button></div>`;
 renderExtras();
}
function extraCalc(x){const t=S(x.tipe_perhitungan||x.tipe||'qty').toLowerCase(),qty=Math.max(1,N(x.qty)||1),w=N(x.lebar),h=N(x.tinggi),l=N(x.panjang),p=Math.max(0,N(x.harga)),d=days(x.tanggal_mulai,x.tanggal_selesai);const basis=t==='luas'?w*h:t==='level'?w:t==='rigging'?((l*2)+(h*2)):qty;return{durasi:t==='overtime'?1:d,basis,subtotal:basis*p*(t==='overtime'?1:d)}}
function renderExtras(){const c=document.querySelector('#invoiceExtras');if(!c||!current)return;c.innerHTML=current.extras.map((x,i)=>`<div class="card" data-extra-index="${i}" style="margin-bottom:10px"><div class="grid g2"><div class="field"><label>Item</label><input data-extra-field="nama_item" value="${E(x.nama_item||'')}"></div><div class="field"><label>Harga</label><input type="number" data-extra-field="harga" value="${N(x.harga)}"></div><div class="field"><label>Qty</label><input type="number" min="0" data-extra-field="qty" value="${N(x.qty)||1}"></div><div class="field"><label>Satuan</label><input data-extra-field="satuan" value="${E(x.satuan||'unit')}"></div><div class="field"><label>Tipe</label><select data-extra-field="tipe_perhitungan"><option value="qty" ${S(x.tipe_perhitungan)==='qty'?'selected':''}>Qty</option><option value="luas" ${S(x.tipe_perhitungan)==='luas'?'selected':''}>Luas</option><option value="rigging" ${S(x.tipe_perhitungan)==='rigging'?'selected':''}>Rigging</option><option value="overtime" ${S(x.tipe_perhitungan)==='overtime'?'selected':''}>Overtime</option></select></div><div class="field"><label>Subtotal</label><input value="${M(x.subtotal)}" readonly></div><div class="field"><label>Lebar</label><input type="number" data-extra-field="lebar" value="${N(x.lebar)}"></div><div class="field"><label>Tinggi / Jam</label><input type="number" data-extra-field="tinggi" value="${N(x.tinggi)}"></div><div class="actions"><button class="btn sm danger" type="button" onclick="invoiceRemoveItem(${i})">Hapus</button></div></div></div>`).join('')||'<div class="empty">Belum ada item tambahan.</div>';
c.querySelectorAll('[data-extra-index]').forEach(card=>{card.querySelectorAll('[data-extra-field]').forEach(el=>el.oninput=()=>syncExtraCard(card));syncExtraCard(card)});}
function syncExtraCard(card){const i=Number(card.dataset.extraIndex),x=current.extras[i];if(!x)return;card.querySelectorAll('[data-extra-field]').forEach(el=>{x[el.dataset.extraField]=el.value});const c=extraCalc(x);x.durasi=c.durasi;x.basis=c.basis;x.subtotal=Math.round(c.subtotal);const out=[...card.querySelectorAll('input')].find(el=>!el.dataset.extraField);if(out)out.value=M(x.subtotal);document.querySelector('#invExtraTotal').textContent=M(extraTotal(current.extras));const total=quoteTotal(current.q)+extraTotal(current.extras);const paid=paymentTotal((window.__PM_INVOICE_CACHE||{}).payments||[],current.id);document.querySelector('#invTotal').textContent=M(total);document.querySelector('#invBalance').textContent=M(Math.max(0,total-paid));}
function invoiceAddItem(){if(!current)return;current.extras.push({master_harga_id:null,kode:'ADD-INV',nama_item:'Item Tambahan',source:'manual',tipe_perhitungan:'qty',qty:1,satuan:'unit',harga:0,lebar:null,tinggi:null,panjang:null,tanggal_mulai:current.q.tanggal_mulai,tanggal_selesai:current.q.tanggal_selesai,durasi:1,basis:1,subtotal:0});renderExtras()}
function invoiceAddOvertime(){if(!current)return;current.extras.push({master_harga_id:null,kode:'ADD-OT',nama_item:'Overtime',source:'manual',tipe_perhitungan:'overtime',qty:1,satuan:'jam',harga:0,lebar:null,tinggi:1,panjang:null,tanggal_mulai:current.q.tanggal_mulai,tanggal_selesai:current.q.tanggal_mulai,durasi:1,basis:1,subtotal:0});renderExtras()}
function invoiceRemoveItem(i){if(!current)return;current.extras.splice(i,1);renderExtras()}
async function saveInvoice(){if(!current)return;const d=DB();if(!d)return msg('Supabase belum terhubung.');try{const payload={nomor_invoice:S(current.q.nomor_invoice),tanggal_invoice:S(document.querySelector('#invDate')?.value),jatuh_tempo:S(document.querySelector('#invDue')?.value),status_invoice:S(document.querySelector('#invStatus')?.value||'DRAFT'),catatan_invoice:S(document.querySelector('#invNotes')?.value)};const items=current.extras.map(x=>({master_harga_id:x.master_harga_id??null,kode:S(x.kode||'ADD-INV'),nama_item:S(x.nama_item||'Item Tambahan'),source:S(x.source||'manual'),tipe_perhitungan:S(x.tipe_perhitungan||'qty'),qty:Math.max(0,N(x.qty)||1),satuan:S(x.satuan||'unit'),harga:Math.max(0,N(x.harga)),lebar:x.lebar==null?null:N(x.lebar),tinggi:x.tinggi==null?null:N(x.tinggi),panjang:x.panjang==null?null:N(x.panjang),tanggal_mulai:x.tanggal_mulai||null,tanggal_selesai:x.tanggal_selesai||null,durasi:Math.max(1,N(x.durasi)||1),basis:Math.max(0,N(x.basis)||1),subtotal:Math.max(0,N(x.subtotal))}));const r=await d.rpc('save_invoice_atomic',{p_penawaran_id:current.id,p_invoice:payload,p_items:items});if(r.error)throw r.error;msg('Invoice berhasil disimpan.');await invoicePage();}catch(e){console.error('[PM] invoice save',e);msg('Gagal menyimpan invoice: '+(e.message||e))}}
async function invoiceEdit(id){await openForm(Number(id))}
async function inputPayment(id){const data=window.__PM_INVOICE_CACHE||await loadData(),q=data.quotes.find(x=>Number(x.id)===Number(id));if(!q)return msg('Penawaran tidak ditemukan.');const ex=data.extras.get(String(id))||[],total=invoiceTotal(q,ex),paid=paymentTotal(data.payments,id),balance=Math.max(0,total-paid);if(balance<=0)return msg('Tidak ada sisa pembayaran.');const nominal=Number(prompt(`Sisa tagihan ${M(balance)}\n\nMasukkan nominal pembayaran:`,String(balance)));if(!Number.isFinite(nominal)||nominal<=0)return;const jenis=paid>0?'PELUNASAN':'DP';const method=prompt('Metode pembayaran (opsional):','Transfer')||null;const d=DB();const r=await d.from('pembayaran_penawaran').insert([{penawaran_id:id,tanggal_bayar:new Date().toISOString().slice(0,10),jenis,nominal,metode:method,catatan:null}]);if(r.error)return msg('Gagal menyimpan pembayaran: '+r.error.message);msg('Pembayaran berhasil dicatat.');await invoicePage()}
async function inputDP(id){return inputPayment(id)}
async function inputPelunasan(id){return inputPayment(id)}
async function previewForId(id){await openForm(id);setTimeout(()=>previewInvoice(),100)}
async function loadTemplate(){const d=DB();if(!d)return{};const r=await d.from('template_surat').select('*').eq('aktif',true).order('id',{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data)return{};window.template=r.data;return r.data}
async function previewInvoice(){if(!current)return;await loadTemplate();const q=current.q,total=invoiceTotal(q,current.extras),paid=paymentTotal((window.__PM_INVOICE_CACHE||{}).payments||[],current.id),extra=extraTotal(current.extras);const root=document.createElement('div');root.id='pmInvoicePreview';root.innerHTML=`<div class="pm-inv-box"><div class="pm-doc-tag"><strong>${E(q.nomor_invoice||'Invoice')}</strong></div><h2>INVOICE</h2><div class="pm-inv-client"><b>${E(q.nama_client||'-')}</b><br>${E(q.perusahaan||'')}<br>${E(q.alamat||'')}</div><p>Referensi Penawaran / Event: ${E(q.nomor_penawaran||'-')} • ${E(q.nama_event||q.event_name||'-')}</p><table class="pm-inv-table table"><thead><tr><th>No</th><th>Item</th><th>Qty</th><th>Harga</th><th>Subtotal</th></tr></thead><tbody><tr><td>1</td><td><strong>Penawaran ${E(q.nomor_penawaran||'-')}</strong></td><td>1</td><td>${M(quoteTotal(q))}</td><td>${M(quoteTotal(q))}</td></tr>${current.extras.map((x,i)=>`<tr class="pm-cust-extra"><td>${i+2}</td><td><strong>${E(x.nama_item||'-')}</strong></td><td>${E(x.qty||1)} ${E(x.satuan||'')}</td><td>${M(x.harga)}</td><td>${M(x.subtotal)}</td></tr>`).join('')}<tr class="pm-inv-extra-total"><td colspan="4">Tambahan</td><td>${M(extra)}</td></tr><tr class="pm-inv-total"><td colspan="4"><strong>TOTAL</strong></td><td>${M(total)}</td></tr></tbody></table><div class="pm-inv-payment"><p>Sudah Dibayar: <b>${M(paid)}</b></p><p>Sisa: <b>${M(Math.max(0,total-paid))}</b></p></div>${window.template?.ketentuan?`<div class="pm-inv-terms">${E(window.template.ketentuan).replace(/\n/g,'<br>')}</div>`:''}${window.template?.nama_penandatangan?`<div class="pm-inv-sign">${E(window.template.nama_penandatangan)}<br><span>${E(window.template.jabatan_penandatangan||'')}</span></div>`:''}</div>`;document.body.appendChild(root);window.__PM_CURRENT_INVOICE_PREVIEW=root;const close=()=>{root.remove();window.__PM_CURRENT_INVOICE_PREVIEW=null};root.addEventListener('click',e=>{if(e.target===root)close()});root.insertAdjacentHTML('beforeend','<div class="pm-print-toolbar"><button class="btn secondary" type="button" id="pmCloseInvoicePreview">Tutup</button><button class="btn green" type="button" id="pmPrintInvoice">Cetak</button></div>');root.querySelector('#pmCloseInvoicePreview').onclick=close;root.querySelector('#pmPrintInvoice').onclick=()=>{document.title=`Invoice - ${q.nama_event||'event'} - ${q.nomor_invoice||'Invoice'}`;window.print()};}
window.invoicePage=invoicePage;window.invoiceEdit=id=>openForm(Number(id));window.invoiceAddItem=invoiceAddItem;window.invoiceAddOvertime=invoiceAddOvertime;window.invoiceRemoveItem=invoiceRemoveItem;window.saveInvoice=saveInvoice;window.inputDP=inputPayment;window.inputPelunasan=inputPayment;window.previewInvoice=previewInvoice;window.previewInvoiceById=previewForId;
const nav=document.querySelector('[data-p="invoice"]');if(nav&&!nav.dataset.pmInvoiceCore){nav.dataset.pmInvoiceCore='1';nav.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();invoicePage()},true)}
})();