-- Priangan Multimedia — production schema contract
-- Audited against Supabase production project iwpnectwkrchjirxakbt on 2026-09-16.
-- IMPORTANT: applied migrations remain the authoritative change history.
-- This file documents the current base-table contract and intentionally retained indexes.
-- Do not add a new JS workaround when a database contract needs to change: create a migration.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nama_client text not null,
  perusahaan text,
  telepon_wa text,
  email text,
  alamat text,
  catatan text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  nama text,
  telepon text,
  whatsapp text
);

create table if not exists public.master_harga (
  id bigint generated by default as identity primary key,
  kode text not null unique,
  kategori text,
  item text not null,
  satuan text,
  harga_jual numeric default 0,
  spesifikasi text,
  isi_paket text,
  keterangan text,
  aktif boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  harga_modal numeric not null default 0
);

create table if not exists public.penawaran (
  id bigint generated by default as identity primary key,
  nomor_penawaran text unique,
  client_id bigint references public.clients(id),
  nama_client text,
  perusahaan text,
  telepon_wa text,
  nama_event text not null,
  tanggal_mulai date,
  tanggal_selesai date,
  status text default 'DRAFT',
  subtotal numeric default 0,
  diskon numeric default 0,
  total numeric default 0,
  catatan text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  alamat text,
  telepon text,
  whatsapp text,
  email text,
  event_name text,
  event text,
  project text,
  tanggal date,
  tanggal_penawaran date,
  diskon_persen numeric not null default 0,
  diskon_nominal numeric not null default 0,
  grand_total numeric not null default 0,
  total_dibayar numeric not null default 0,
  sisa_pembayaran numeric not null default 0,
  status_pembayaran text not null default 'BELUM BAYAR',
  nomor_invoice text,
  tanggal_invoice date,
  jatuh_tempo date,
  status_invoice text,
  catatan_invoice text
);

create table if not exists public.penawaran_items (
  id bigint generated by default as identity primary key,
  penawaran_id bigint not null references public.penawaran(id) on delete cascade,
  master_harga_id bigint references public.master_harga(id),
  kode text,
  nama_item text,
  kategori text,
  satuan text,
  harga numeric default 0,
  tipe_perhitungan text default 'QTY',
  lebar numeric,
  tinggi numeric,
  panjang numeric,
  created_at timestamptz default now(),
  item text,
  harga_modal numeric not null default 0,
  harga_jual numeric not null default 0,
  qty numeric not null default 1,
  jumlah numeric not null default 1,
  durasi numeric not null default 1,
  tipe text,
  subtotal numeric not null default 0,
  tanggal_mulai date,
  tanggal_selesai date,
  diskon_persen numeric not null default 0,
  diskon_nominal numeric not null default 0,
  level_enabled boolean not null default false,
  level_master_harga_id bigint,
  level_tinggi numeric,
  level_harga numeric,
  level_subtotal numeric not null default 0
);

create table if not exists public.penawaran_jadwal (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.penawaran_items(id) on delete cascade,
  qty numeric default 1,
  tanggal_mulai date not null,
  tanggal_selesai date not null,
  durasi_hari integer,
  subtotal numeric default 0,
  created_at timestamptz default now(),
  penawaran_id bigint,
  penawaran_item_id bigint,
  durasi numeric
);

create table if not exists public.pembayaran_penawaran (
  id bigint generated by default as identity primary key,
  penawaran_id bigint not null references public.penawaran(id) on delete cascade,
  tanggal_bayar date not null default current_date,
  jenis text not null default 'DP',
  nominal numeric not null default 0,
  metode text,
  catatan text,
  created_at timestamptz not null default now(),
  constraint pembayaran_penawaran_jenis_check check (jenis in ('DP','PELUNASAN','LAINNYA')),
  constraint pembayaran_penawaran_nominal_nonnegative check (nominal >= 0)
);

create table if not exists public.penawaran_invoice_items (
  id bigint generated by default as identity primary key,
  penawaran_id bigint not null references public.penawaran(id) on delete cascade,
  master_harga_id bigint references public.master_harga(id) on delete set null,
  kode text,
  nama_item text not null,
  source text not null default 'manual',
  tipe_perhitungan text not null default 'qty',
  qty numeric not null default 1,
  satuan text,
  harga numeric not null default 0,
  lebar numeric,
  tinggi numeric,
  panjang numeric,
  tanggal_mulai date,
  tanggal_selesai date,
  durasi numeric not null default 1,
  basis numeric not null default 1,
  subtotal numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint penawaran_invoice_items_basis_check check (basis >= 0),
  constraint penawaran_invoice_items_durasi_check check (durasi > 0),
  constraint penawaran_invoice_items_harga_check check (harga >= 0),
  constraint penawaran_invoice_items_qty_check check (qty >= 0),
  constraint penawaran_invoice_items_subtotal_check check (subtotal >= 0)
);

create table if not exists public.pengeluaran_keuangan (
  id bigint generated by default as identity primary key,
  tanggal date not null default current_date,
  nominal numeric not null default 0,
  keperluan text not null,
  catatan text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pengeluaran_keuangan_nominal_check check (nominal >= 0)
);

create table if not exists public.template_surat (
  id bigint generated by default as identity primary key,
  nama_template text not null,
  logo_url text,
  kop_text text,
  alamat text,
  telepon text,
  whatsapp text,
  email text,
  website text,
  ketentuan text,
  footer_text text,
  nama_penandatangan text,
  jabatan_penandatangan text,
  tanda_tangan_url text,
  aktif boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  ttd_url text
);

create table if not exists public.vendors (
  id bigint generated by default as identity primary key,
  nama text not null,
  vendor text not null,
  telepon text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Production indexes intentionally retained after the 2026-09-16 index audit.
create index if not exists idx_clients_nama on public.clients (nama_client);
create index if not exists idx_master_harga_aktif on public.master_harga (aktif);
create index if not exists idx_master_harga_kategori on public.master_harga (kategori);
create index if not exists idx_master_harga_kode on public.master_harga (kode);
create index if not exists idx_pembayaran_penawaran_penawaran_id on public.pembayaran_penawaran (penawaran_id);
create index if not exists idx_pembayaran_penawaran_tanggal on public.pembayaran_penawaran (tanggal_bayar);
create index if not exists idx_penawaran_client on public.penawaran (client_id);
create index if not exists idx_penawaran_nomor on public.penawaran (nomor_penawaran);
create index if not exists idx_penawaran_status on public.penawaran (status);
create index if not exists idx_penawaran_tanggal on public.penawaran (tanggal);
create index if not exists idx_penawaran_invoice_items_master_harga_id on public.penawaran_invoice_items (master_harga_id);
create index if not exists idx_penawaran_invoice_items_penawaran_id on public.penawaran_invoice_items (penawaran_id);
create index if not exists idx_penawaran_items_kode on public.penawaran_items (kode);
create index if not exists idx_penawaran_items_master_harga_id on public.penawaran_items (master_harga_id);
create index if not exists idx_penawaran_items_penawaran on public.penawaran_items (penawaran_id);
create index if not exists idx_jadwal_item on public.penawaran_jadwal (item_id);
create index if not exists idx_penawaran_jadwal_penawaran on public.penawaran_jadwal (penawaran_id);
create index if not exists idx_pengeluaran_keuangan_tanggal on public.pengeluaran_keuangan (tanggal);

-- Current production views:
-- v_client_app, v_daftar_penawaran_app, v_dashboard_keuangan, v_item_master_picker,
-- v_keuangan_app, v_master_harga_app, v_pembayaran_app, v_penawaran_app,
-- v_penawaran_detail_app.
-- Their definitions are maintained by migrations because views depend on the table contract.

-- Current production calculation/trigger functions:
-- hitung_penawaran(bigint)
-- trigger_hitung_penawaran_items()
-- trigger_hitung_penawaran_jadwal()
-- trigger_hitung_penawaran_pembayaran()
-- sync_penawaran_discount_fields()
-- rls_auto_enable()

-- Current production triggers:
-- trg_hitung_penawaran_pembayaran
-- trg_sync_penawaran_discount_fields
-- trg_hitung_penawaran_items
-- trg_hitung_penawaran_jadwal
