create table if not exists public.clients(id bigint generated by default as identity primary key,nama_client text,perusahaan text,telepon text,whatsapp text,email text,alamat text,created_at timestamptz default now());
create table if not exists public.penawaran(id bigint generated by default as identity primary key,nomor_penawaran text,nama_client text,perusahaan text,telepon text,whatsapp text,email text,event_name text,tanggal_mulai date,tanggal_selesai date,total numeric default 0,status text default 'DRAFT',created_at timestamptz default now());
create table if not exists public.penawaran_items(id bigint generated by default as identity primary key,penawaran_id bigint references public.penawaran(id) on delete cascade,kode text,item text,harga_jual numeric default 0,tipe_perhitungan text,qty numeric default 1,lebar numeric,tinggi numeric,panjang numeric,subtotal numeric default 0,created_at timestamptz default now());
create table if not exists public.penawaran_jadwal(id bigint generated by default as identity primary key,penawaran_item_id bigint references public.penawaran_items(id) on delete cascade,qty numeric default 1,tanggal_mulai date,tanggal_selesai date,durasi numeric,subtotal numeric default 0,created_at timestamptz default now());
alter table public.template_surat add column if not exists website text;
alter table public.template_surat add column if not exists ketentuan text;
alter table public.template_surat add column if not exists nama_penandatangan text;
alter table public.template_surat add column if not exists jabatan_penandatangan text;
alter table public.template_surat add column if not exists ttd_url text;
