-- Priangan Multimedia: schema hardening / canonical quotation schema
-- Idempotent: safe to run more than once.

create table if not exists public.master_harga (
  id bigint generated by default as identity primary key,
  kode text,
  item text,
  kategori text default '',
  satuan text default '',
  harga_modal numeric not null default 0,
  harga_jual numeric not null default 0,
  aktif boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.master_harga add column if not exists kode text;
alter table public.master_harga add column if not exists item text;
alter table public.master_harga add column if not exists kategori text default '';
alter table public.master_harga add column if not exists satuan text default '';
alter table public.master_harga add column if not exists harga_modal numeric default 0;
alter table public.master_harga add column if not exists harga_jual numeric default 0;
alter table public.master_harga add column if not exists aktif boolean default true;
alter table public.master_harga add column if not exists created_at timestamptz default now();
alter table public.master_harga add column if not exists updated_at timestamptz default now();

update public.master_harga
set harga_modal = coalesce(harga_modal, 0),
    harga_jual = coalesce(harga_jual, 0),
    aktif = coalesce(aktif, true);

create index if not exists idx_master_harga_kode on public.master_harga(kode);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  nama_client text default '',
  perusahaan text default '',
  telepon text default '',
  whatsapp text default '',
  email text default '',
  alamat text default '',
  created_at timestamptz default now()
);

alter table public.clients add column if not exists nama_client text default '';
alter table public.clients add column if not exists perusahaan text default '';
alter table public.clients add column if not exists telepon text default '';
alter table public.clients add column if not exists whatsapp text default '';
alter table public.clients add column if not exists email text default '';
alter table public.clients add column if not exists alamat text default '';

create table if not exists public.penawaran (
  id bigint generated by default as identity primary key,
  nomor_penawaran text default '',
  nama_client text default '',
  perusahaan text default '',
  telepon text default '',
  whatsapp text default '',
  email text default '',
  event_name text default '',
  tanggal_mulai date,
  tanggal_selesai date,
  total numeric default 0,
  status text default 'DRAFT',
  created_at timestamptz default now()
);

alter table public.penawaran add column if not exists nomor_penawaran text default '';
alter table public.penawaran add column if not exists nama_client text default '';
alter table public.penawaran add column if not exists perusahaan text default '';
alter table public.penawaran add column if not exists telepon text default '';
alter table public.penawaran add column if not exists whatsapp text default '';
alter table public.penawaran add column if not exists email text default '';
alter table public.penawaran add column if not exists event_name text default '';
alter table public.penawaran add column if not exists tanggal_mulai date;
alter table public.penawaran add column if not exists tanggal_selesai date;
alter table public.penawaran add column if not exists total numeric default 0;
alter table public.penawaran add column if not exists status text default 'DRAFT';
alter table public.penawaran add column if not exists created_at timestamptz default now();

-- Backward-compatible aliases used by older deployed builds.
alter table public.penawaran add column if not exists nama_event text default '';
alter table public.penawaran add column if not exists event text default '';
alter table public.penawaran add column if not exists project text default '';
alter table public.penawaran add column if not exists grand_total numeric default 0;
alter table public.penawaran add column if not exists subtotal numeric default 0;
alter table public.penawaran add column if not exists diskon numeric default 0;
alter table public.penawaran add column if not exists discount numeric default 0;
alter table public.penawaran add column if not exists nilai_diskon numeric default 0;
alter table public.penawaran add column if not exists persen_diskon numeric default 0;
alter table public.penawaran add column if not exists discount_percent numeric default 0;
alter table public.penawaran add column if not exists tanggal date;
alter table public.penawaran add column if not exists tanggal_penawaran date;

update public.penawaran
set nama_event = coalesce(nullif(nama_event, ''), event_name, ''),
    event = coalesce(nullif(event, ''), event_name, ''),
    project = coalesce(nullif(project, ''), event_name, ''),
    grand_total = coalesce(grand_total, total, 0),
    tanggal_penawaran = coalesce(tanggal_penawaran, tanggal, created_at::date),
    tanggal = coalesce(tanggal, tanggal_penawaran, created_at::date),
    diskon = coalesce(diskon, 0),
    discount = coalesce(discount, diskon, 0),
    nilai_diskon = coalesce(nilai_diskon, diskon, 0),
    persen_diskon = coalesce(persen_diskon, 0),
    discount_percent = coalesce(discount_percent, persen_diskon, 0);

create index if not exists idx_penawaran_status on public.penawaran(status);
create index if not exists idx_penawaran_created_at on public.penawaran(created_at desc);

create table if not exists public.penawaran_items (
  id bigint generated by default as identity primary key,
  penawaran_id bigint references public.penawaran(id) on delete cascade,
  kode text default '',
  item text default '',
  harga_jual numeric default 0,
  tipe_perhitungan text default 'qty',
  qty numeric default 1,
  lebar numeric,
  tinggi numeric,
  panjang numeric,
  subtotal numeric default 0,
  created_at timestamptz default now()
);

alter table public.penawaran_items add column if not exists kode text default '';
alter table public.penawaran_items add column if not exists item text default '';
alter table public.penawaran_items add column if not exists nama_item text default '';
alter table public.penawaran_items add column if not exists harga_jual numeric default 0;
alter table public.penawaran_items add column if not exists harga numeric default 0;
alter table public.penawaran_items add column if not exists harga_modal numeric default 0;
alter table public.penawaran_items add column if not exists tipe_perhitungan text default 'qty';
alter table public.penawaran_items add column if not exists tipe text default 'qty';
alter table public.penawaran_items add column if not exists qty numeric default 1;
alter table public.penawaran_items add column if not exists jumlah numeric default 1;
alter table public.penawaran_items add column if not exists lebar numeric;
alter table public.penawaran_items add column if not exists tinggi numeric;
alter table public.penawaran_items add column if not exists panjang numeric;
alter table public.penawaran_items add column if not exists tanggal_mulai date;
alter table public.penawaran_items add column if not exists tanggal_selesai date;
alter table public.penawaran_items add column if not exists durasi numeric default 1;
alter table public.penawaran_items add column if not exists subtotal numeric default 0;

update public.penawaran_items
set nama_item = coalesce(nullif(nama_item, ''), item, ''),
    harga = coalesce(harga, harga_jual, 0),
    tipe = coalesce(nullif(tipe, ''), tipe_perhitungan, 'qty'),
    jumlah = coalesce(jumlah, qty, 1),
    qty = coalesce(qty, jumlah, 1),
    harga_modal = coalesce(harga_modal, 0);

create index if not exists idx_penawaran_items_penawaran on public.penawaran_items(penawaran_id);

create table if not exists public.penawaran_jadwal (
  id bigint generated by default as identity primary key,
  penawaran_item_id bigint references public.penawaran_items(id) on delete cascade,
  qty numeric default 1,
  tanggal_mulai date,
  tanggal_selesai date,
  durasi numeric default 1,
  subtotal numeric default 0,
  created_at timestamptz default now()
);

alter table public.penawaran_jadwal add column if not exists qty numeric default 1;
alter table public.penawaran_jadwal add column if not exists jumlah numeric default 1;
alter table public.penawaran_jadwal add column if not exists tanggal_mulai date;
alter table public.penawaran_jadwal add column if not exists tanggal_selesai date;
alter table public.penawaran_jadwal add column if not exists durasi numeric default 1;
alter table public.penawaran_jadwal add column if not exists subtotal numeric default 0;

alter table public.template_surat add column if not exists website text;
alter table public.template_surat add column if not exists ketentuan text;
alter table public.template_surat add column if not exists nama_penandatangan text;
alter table public.template_surat add column if not exists jabatan_penandatangan text;
alter table public.template_surat add column if not exists ttd_url text;

notify pgrst, 'reload schema';
