-- ============================================================
-- EVENT FINANCE + DP / PAYMENT TRACKING
-- ============================================================
BEGIN;

ALTER TABLE public.penawaran
  ADD COLUMN IF NOT EXISTS total_dibayar numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sisa_pembayaran numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status_pembayaran text NOT NULL DEFAULT 'BELUM BAYAR';

CREATE TABLE IF NOT EXISTS public.pembayaran_penawaran (
  id bigint generated by default as identity primary key,
  penawaran_id bigint NOT NULL,
  tanggal_bayar date NOT NULL DEFAULT CURRENT_DATE,
  jenis text NOT NULL DEFAULT 'DP',
  nominal numeric NOT NULL DEFAULT 0,
  metode text,
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pembayaran_penawaran_id
  ON public.pembayaran_penawaran(penawaran_id);

CREATE INDEX IF NOT EXISTS idx_pembayaran_tanggal
  ON public.pembayaran_penawaran(tanggal_bayar);

-- Refresh PostgREST schema cache.
NOTIFY pgrst, 'reload schema';
COMMIT;

-- Verification
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema='public'
  AND table_name='pembayaran_penawaran'
ORDER BY ordinal_position;
