-- ============================================================
-- FIX: PAYMENT TABLE FOR DP + PELUNASAN
-- Jalankan SEKALI di Supabase SQL Editor.
-- ============================================================
BEGIN;

-- Ringkasan pembayaran pada penawaran.
ALTER TABLE public.penawaran
  ADD COLUMN IF NOT EXISTS total_dibayar numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sisa_pembayaran numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status_pembayaran text NOT NULL DEFAULT 'BELUM BAYAR';

-- Detail transaksi pembayaran. DP dan PELUNASAN disimpan sebagai
-- dua transaksi berbeda berdasarkan kolom jenis.
CREATE TABLE IF NOT EXISTS public.pembayaran_penawaran (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penawaran_id bigint NOT NULL,
  tanggal_bayar date NOT NULL DEFAULT CURRENT_DATE,
  jenis text NOT NULL DEFAULT 'DP',
  nominal numeric NOT NULL DEFAULT 0,
  metode text,
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Jika tabel sudah pernah dibuat tetapi kolom belum lengkap.
ALTER TABLE public.pembayaran_penawaran
  ADD COLUMN IF NOT EXISTS penawaran_id bigint,
  ADD COLUMN IF NOT EXISTS tanggal_bayar date NOT NULL DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS jenis text NOT NULL DEFAULT 'DP',
  ADD COLUMN IF NOT EXISTS nominal numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metode text,
  ADD COLUMN IF NOT EXISTS catatan text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_pembayaran_penawaran_penawaran_id
  ON public.pembayaran_penawaran(penawaran_id);

CREATE INDEX IF NOT EXISTS idx_pembayaran_penawaran_tanggal
  ON public.pembayaran_penawaran(tanggal_bayar);

-- Pastikan nominal tidak negatif.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pembayaran_penawaran_nominal_nonnegative'
      AND conrelid = 'public.pembayaran_penawaran'::regclass
  ) THEN
    ALTER TABLE public.pembayaran_penawaran
      ADD CONSTRAINT pembayaran_penawaran_nominal_nonnegative CHECK (nominal >= 0);
  END IF;
END $$;

-- Hanya dua fungsi pembayaran utama yang digunakan aplikasi.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pembayaran_penawaran_jenis_check'
      AND conrelid = 'public.pembayaran_penawaran'::regclass
  ) THEN
    ALTER TABLE public.pembayaran_penawaran
      ADD CONSTRAINT pembayaran_penawaran_jenis_check
      CHECK (jenis IN ('DP','PELUNASAN','LAINNYA'));
  END IF;
END $$;

-- Aplikasi browser memakai Supabase anon key. RLS sengaja tidak diaktifkan
-- oleh migration ini supaya tidak memblokir transaksi aplikasi yang sudah ada.
NOTIFY pgrst, 'reload schema';

COMMIT;

-- VERIFIKASI
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'pembayaran_penawaran'
ORDER BY ordinal_position;
