-- PRIANGAN MULTIMEDIA
-- FIX FINAL akses pembayaran_penawaran untuk web app berbasis Supabase anon key.
-- Jalankan SELURUH script ini di Supabase SQL Editor.
--
-- Catatan: aplikasi ini belum memakai autentikasi user untuk transaksi internal.
-- Karena itu RLS pada tabel transaksi pembayaran dinonaktifkan agar tidak ada
-- policy lama/restrictive yang diam-diam memblokir INSERT dari browser.

BEGIN;

-- Pastikan tabel dan kolom inti tersedia.
CREATE TABLE IF NOT EXISTS public.pembayaran_penawaran (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  penawaran_id bigint NOT NULL,
  tanggal_bayar date NOT NULL DEFAULT CURRENT_DATE,
  jenis text NOT NULL DEFAULT 'DP',
  nominal numeric NOT NULL DEFAULT 0,
  metode text,
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.pembayaran_penawaran
  ADD COLUMN IF NOT EXISTS penawaran_id bigint,
  ADD COLUMN IF NOT EXISTS tanggal_bayar date NOT NULL DEFAULT CURRENT_DATE,
  ADD COLUMN IF NOT EXISTS jenis text NOT NULL DEFAULT 'DP',
  ADD COLUMN IF NOT EXISTS nominal numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metode text,
  ADD COLUMN IF NOT EXISTS catatan text,
  ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

-- Ringkasan pembayaran pada penawaran.
ALTER TABLE public.penawaran
  ADD COLUMN IF NOT EXISTS total_dibayar numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sisa_pembayaran numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status_pembayaran text NOT NULL DEFAULT 'BELUM BAYAR';

-- Bersihkan policy lama, termasuk policy dengan nama yang tidak kita kenal.
DO $$
DECLARE p record;
BEGIN
  FOR p IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname='public' AND tablename='pembayaran_penawaran'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.pembayaran_penawaran', p.policyname);
  END LOOP;
END $$;

-- Nonaktifkan RLS supaya anon key dapat melakukan transaksi internal aplikasi.
ALTER TABLE public.pembayaran_penawaran DISABLE ROW LEVEL SECURITY;

-- Hak akses PostgREST untuk browser.
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.pembayaran_penawaran TO anon, authenticated;

DO $$
DECLARE seq_name text;
BEGIN
  SELECT pg_get_serial_sequence('public.pembayaran_penawaran','id') INTO seq_name;
  IF seq_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', seq_name);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pembayaran_penawaran_penawaran_id
  ON public.pembayaran_penawaran(penawaran_id);

CREATE INDEX IF NOT EXISTS idx_pembayaran_penawaran_tanggal
  ON public.pembayaran_penawaran(tanggal_bayar);

-- Validasi transaksi.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='pembayaran_penawaran_nominal_nonnegative'
      AND conrelid='public.pembayaran_penawaran'::regclass
  ) THEN
    ALTER TABLE public.pembayaran_penawaran
      ADD CONSTRAINT pembayaran_penawaran_nominal_nonnegative CHECK (nominal >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='pembayaran_penawaran_jenis_check'
      AND conrelid='public.pembayaran_penawaran'::regclass
  ) THEN
    ALTER TABLE public.pembayaran_penawaran
      ADD CONSTRAINT pembayaran_penawaran_jenis_check
      CHECK (jenis IN ('DP','PELUNASAN','LAINNYA'));
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
COMMIT;

-- VERIFIKASI: harus mengembalikan rls_enabled = false.
SELECT
  c.relname AS table_name,
  c.relrowsecurity AS rls_enabled,
  has_table_privilege('anon', 'public.pembayaran_penawaran', 'INSERT') AS anon_can_insert,
  has_table_privilege('anon', 'public.pembayaran_penawaran', 'SELECT') AS anon_can_select
FROM pg_class c
JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relname='pembayaran_penawaran';